from datetime import datetime

from flext_core import FlextResult

__all__ = [
    "add_hours_to_now",
    "add_minutes_to_now",
    "create_error_result",
    "extract_dict_value",
    "filter_sensitive_data",
    "generate_secure_password",
    "generate_secure_token",
    "get_utc_now",
    "handle_exception",
    "is_expired",
    "is_strong_password",
    "is_valid_email_format",
    "mask_sensitive_data",
    "safe_bool",
    "safe_int",
    "safe_str",
    "sanitize_input",
]

def generate_secure_token(length: int = 32) -> str: ...
def generate_secure_password(length: int = 16) -> str: ...
def mask_sensitive_data(data: str, visible_chars: int = 4) -> str: ...
def get_utc_now() -> datetime: ...
def is_expired(expires_at: datetime) -> bool: ...
def add_minutes_to_now(minutes: int) -> datetime: ...
def add_hours_to_now(hours: int) -> datetime: ...
def is_valid_email_format(email: str) -> bool: ...
def is_strong_password(password: str) -> bool: ...
def sanitize_input(input_str: str) -> str: ...
def safe_str(value: object) -> str: ...
def safe_int(value: object, default: int = 0) -> int: ...
def safe_bool(value: object, *, default: bool = False) -> bool: ...
def extract_dict_value(
    data: dict[str, object], key: str, default: object = None
) -> object: ...
def filter_sensitive_data(data: dict[str, object]) -> dict[str, object]: ...
def create_error_result(
    message: str, error_code: str = "AUTH_ERROR"
) -> FlextResult[None]: ...
def handle_exception(
    e: Exception, operation: str = "operation"
) -> FlextResult[None]: ...
