from abc import ABC, abstractmethod

from flext_core import FlextResult

from flext_auth.auth_models import FlextSession

__all__ = ["InMemorySessionRepository", "SessionRepository"]

class SessionRepository(ABC):
    @abstractmethod
    async def save(self, session: FlextSession) -> FlextResult[FlextSession]: ...
    @abstractmethod
    def find_by_id(self, session_id: str) -> FlextResult[FlextSession | None]: ...
    @abstractmethod
    def find_by_user_id(self, user_id: str) -> FlextResult[list[FlextSession]]: ...
    @abstractmethod
    def revoke_all_sessions_for_user(self, user_id: str) -> FlextResult[int]: ...
    @abstractmethod
    def cleanup_expired_sessions(self) -> FlextResult[int]: ...
    async def get_by_id(self, session_id: str) -> FlextResult[FlextSession | None]: ...
    async def get_by_user_id(self, user_id: str) -> FlextResult[list[FlextSession]]: ...
    async def revoke_all_user_sessions(self, user_id: str) -> FlextResult[int]: ...

class InMemorySessionRepository(SessionRepository):
    def __init__(self) -> None: ...
    async def save(self, session: FlextSession) -> FlextResult[FlextSession]: ...
    def find_by_id(self, session_id: str) -> FlextResult[FlextSession | None]: ...
    def find_by_user_id(self, user_id: str) -> FlextResult[list[FlextSession]]: ...
    def revoke_all_sessions_for_user(self, user_id: str) -> FlextResult[int]: ...
    def cleanup_expired_sessions(self) -> FlextResult[int]: ...
    async def get_by_id(self, session_id: str) -> FlextResult[FlextSession | None]: ...
    async def get_by_user_id(self, user_id: str) -> FlextResult[list[FlextSession]]: ...
    async def revoke_session(self, session_id: str) -> FlextResult[bool]: ...
    async def revoke_all_user_sessions(self, user_id: str) -> FlextResult[int]: ...
    def get_active_session_count(self, user_id: str) -> FlextResult[int]: ...
