__all__ = [
    "auth_config",
    "auth_error",
    "auth_service",
    "authentication_error",
    "generate_jwt",
    "hash_password",
    "quick_start",
    "session",
    "user",
    "validate_jwt",
    "validation_error",
    "verify_password",
]

def auth_service(*args: object, **kwargs: object) -> object: ...
def auth_config(*args: object, **kwargs: object) -> object: ...
def user(*args: object, **kwargs: object) -> object: ...
def session(*args: object, **kwargs: object) -> object: ...
def auth_error(*args: object, **kwargs: object) -> object: ...
def validation_error(*args: object, **kwargs: object) -> object: ...
def authentication_error(*args: object, **kwargs: object) -> object: ...
def quick_start(*args: object, **kwargs: object) -> object: ...
def hash_password(*args: object, **kwargs: object) -> object: ...
def verify_password(*args: object, **kwargs: object) -> object: ...
def generate_jwt(*args: object, **kwargs: object) -> object: ...
def validate_jwt(*args: object, **kwargs: object) -> object: ...
