from abc import ABC, abstractmethod

from flext_core import FlextResult

from flext_auth.domain_entities import (
    FlextSession as FlextSession,
    FlextSessionStatus as FlextSessionStatus,
)

class SessionRepository(ABC):
    @abstractmethod
    async def save(self, session: FlextSession) -> FlextResult[FlextSession]: ...
    @abstractmethod
    async def get_by_id(self, session_id: str) -> FlextResult[FlextSession | None]: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: str) -> FlextResult[list[FlextSession]]: ...
    @abstractmethod
    async def get_active_sessions(
        self, user_id: str
    ) -> FlextResult[list[FlextSession]]: ...
    @abstractmethod
    async def revoke_session(self, session_id: str) -> FlextResult[bool]: ...
    @abstractmethod
    async def revoke_all_user_sessions(self, user_id: str) -> FlextResult[int]: ...
    @abstractmethod
    async def cleanup_expired_sessions(self) -> FlextResult[int]: ...
    @abstractmethod
    async def delete(self, session_id: str) -> FlextResult[bool]: ...

class InMemorySessionRepository(SessionRepository):
    def __init__(self) -> None: ...
    async def save(self, session: FlextSession) -> FlextResult[FlextSession]: ...
    def find_by_id(self, session_id: str) -> FlextResult[FlextSession | None]: ...
    def revoke_all_sessions_for_user(self, user_id: str) -> FlextResult[int]: ...
    def save_sync(self, session: FlextSession) -> FlextResult[FlextSession]: ...
    async def get_by_id(self, session_id: str) -> FlextResult[FlextSession | None]: ...
    async def get_by_user_id(self, user_id: str) -> FlextResult[list[FlextSession]]: ...
    async def get_active_sessions(
        self, user_id: str
    ) -> FlextResult[list[FlextSession]]: ...
    async def revoke_session(self, session_id: str) -> FlextResult[bool]: ...
    async def revoke_all_user_sessions(self, user_id: str) -> FlextResult[int]: ...
    async def cleanup_expired_sessions(self) -> FlextResult[int]: ...
    async def delete(self, session_id: str) -> FlextResult[bool]: ...
