from abc import ABC, abstractmethod

from flext_core import FlextResult

from flext_auth.domain_entities import (
    FlextUser as FlextUser,
    FlextUserStatus as FlextUserStatus,
)

class UserRepository(ABC):
    @abstractmethod
    async def save(self, user: FlextUser) -> FlextResult[FlextUser]: ...
    @abstractmethod
    async def get_by_id(self, user_id: str) -> FlextResult[FlextUser | None]: ...
    @abstractmethod
    async def get_by_username(self, username: str) -> FlextResult[FlextUser | None]: ...
    @abstractmethod
    async def get_by_email(self, email: str) -> FlextResult[FlextUser | None]: ...
    @abstractmethod
    async def delete(self, user_id: str) -> FlextResult[bool]: ...
    @abstractmethod
    async def list_users(
        self, limit: int = 100, offset: int = 0, status: FlextUserStatus | None = None
    ) -> FlextResult[list[FlextUser]]: ...
    @abstractmethod
    async def count_users(
        self, status: FlextUserStatus | None = None
    ) -> FlextResult[int]: ...

class InMemoryUserRepository(UserRepository):
    def __init__(self) -> None: ...
    async def save(self, user: FlextUser) -> FlextResult[FlextUser]: ...
    async def get_by_id(self, user_id: str) -> FlextResult[FlextUser | None]: ...
    async def get_by_username(self, username: str) -> FlextResult[FlextUser | None]: ...
    async def get_by_email(self, email: str) -> FlextResult[FlextUser | None]: ...
    async def delete(self, user_id: str) -> FlextResult[bool]: ...
    async def list_users(
        self, limit: int = 100, offset: int = 0, status: FlextUserStatus | None = None
    ) -> FlextResult[list[FlextUser]]: ...
    async def count_users(
        self, status: FlextUserStatus | None = None
    ) -> FlextResult[int]: ...
