EXAMPLE_DEMO_PASSWORD: str
EXAMPLE_JWT_SECRET: str
EXAMPLE_API_SECRET: str
EXAMPLE_SERVICE_SECRET: str
EXAMPLE_MFA_SECRET: str
EXAMPLE_CHECK_SECRET: str
EXAMPLE_DECORATOR_SECRET: str
EXAMPLE_LIFECYCLE_PASSWORD: str
EXAMPLE_BATCH_PASSWORD_1: str
EXAMPLE_BATCH_PASSWORD_2: str

def demo_all_constants_and_configs() -> None: ...
def demo_all_factory_functions() -> None: ...
def demo_all_password_operations() -> None: ...
def demo_all_jwt_operations() -> None: ...
def demo_all_token_types() -> None: ...
def demo_all_session_operations() -> None: ...
def demo_all_role_permission_operations() -> None: ...
def demo_all_validation_operations() -> None: ...
def demo_ultra_helpers() -> None: ...
def demo_decorators() -> None: ...
def demo_mixin_pattern() -> None: ...
async def demo_full_auth_lifecycle() -> None: ...
async def demo_batch_operations() -> None: ...
def demo_type_definitions() -> None: ...
async def main() -> None: ...
