import pytest

def pytest_configure(config: pytest.Config) -> None: ...
def pytest_collection_modifyitems(
    config: pytest.Config, items: list[pytest.Item]
) -> None: ...
@pytest.fixture
def sample_user_id() -> str: ...
@pytest.fixture
def sample_username() -> str: ...
@pytest.fixture
def sample_email() -> str: ...
@pytest.fixture
def sample_password() -> str: ...
@pytest.fixture
def sample_user_data(
    sample_user_id: str, sample_username: str, sample_email: str
) -> dict[str, str | bool]: ...
@pytest.fixture
def sample_users_dict(
    sample_user_data: dict[str, str | bool],
) -> dict[str, dict[str, str | bool]]: ...
