def test_basic_imports() -> bool | None: ...
def test_basic_functionality() -> bool | None: ...
def test_quick_start() -> bool | None: ...
def test_examples_core_functionality() -> bool | None: ...
def main() -> int: ...
