from collections.abc import Callable as Callable

import pytest

from flext_auth import FlextAuth

EXPECTED_DATA_COUNT: int

class TestFlextAuthClassePrincipal:
    @pytest.fixture
    def auth(self) -> FlextAuth: ...
    @pytest.fixture
    def auth_with_config(self) -> FlextAuth: ...
    @pytest.mark.asyncio
    async def test_registro_usuario_sucesso(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_registro_usuario_duplicado(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_login_sucesso(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_login_credenciais_invalidas(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_validacao_token_sucesso(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_validacao_token_invalido(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_logout_sucesso(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_refresh_token_sucesso(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_mudanca_senha_sucesso(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_mudanca_senha_senha_atual_incorreta(
        self, auth: FlextAuth
    ) -> None: ...
    @pytest.mark.asyncio
    async def test_listar_sessoes_usuario(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_limpeza_sessoes_expiradas(self, auth: FlextAuth) -> None: ...

class TestFlextAuthQuickStart:
    def test_quick_start_default(self) -> None: ...
    def test_quick_start_custom_REDACTED_LDAP_BIND_PASSWORD(self) -> None: ...

class TestFlextAuthHelpers:
    def test_hash_password(self) -> None: ...
    def test_hash_password_rounds_customizado(self) -> None: ...
    def test_verify_password_correto(self) -> None: ...
    def test_verify_password_incorreto(self) -> None: ...
    def test_generate_jwt_basico(self) -> None: ...
    def test_generate_jwt_com_expiracao(self) -> None: ...
    def test_decode_jwt_valido(self) -> None: ...
    def test_decode_jwt_invalido(self) -> None: ...
    def test_validate_email_validos(self) -> None: ...
    def test_validate_email_invalidos(self) -> None: ...
    def test_validate_password_strength_forte(self) -> None: ...
    def test_validate_password_strength_fraca(self) -> None: ...
    def test_create_secure_session(self) -> None: ...
    def test_middleware_creator(self) -> None: ...

class TestFlextAuthCompatibilidade:
    def test_deprecated_classes_emit_warnings(self) -> None: ...

class TestFlextAuthIntegracao:
    @pytest.mark.asyncio
    async def test_fluxo_completo_autenticacao(self) -> None: ...
    @pytest.mark.asyncio
    async def test_multiplos_usuarios_simultaneos(self) -> None: ...
    def test_helpers_chain_workflow(self) -> None: ...

class TestFlextAuthPerformance:
    def test_hash_password_performance(self, benchmark: Callable) -> None: ...
    def test_verify_password_performance(self, benchmark: Callable) -> None: ...
    def test_jwt_operations_performance(self, benchmark: Callable) -> None: ...
