import pytest
from _typeshed import Incomplete

class TestFlextAuthService:
    user_repo: Incomplete
    session_repo: Incomplete
    password_service: Incomplete
    jwt_service: Incomplete
    auth_service: Incomplete
    def setup_method(self) -> None: ...
    @pytest.mark.unit
    async def test_register_user_success(self) -> None: ...
    @pytest.mark.unit
    async def test_register_user_duplicate_username(self) -> None: ...
    @pytest.mark.unit
    async def test_register_user_duplicate_email(self) -> None: ...
    @pytest.mark.unit
    async def test_authenticate_user_success(self) -> None: ...
    @pytest.mark.unit
    async def test_authenticate_user_invalid_credentials(self) -> None: ...
    @pytest.mark.unit
    async def test_authenticate_user_nonexistent(self) -> None: ...
    @pytest.mark.unit
    async def test_validate_token_success(self) -> None: ...
    @pytest.mark.unit
    async def test_validate_token_invalid(self) -> None: ...
    @pytest.mark.integration
    async def test_full_authentication_flow(self) -> None: ...
    @pytest.mark.security
    async def test_password_hashing_security(self) -> None: ...
    @pytest.mark.security
    async def test_account_lockout_protection(self) -> None: ...
