EXPECTED_DATA_COUNT: int

def test_flext_auth_hash_password() -> None: ...
def test_flext_auth_jwt_helpers() -> None: ...
def test_flext_auth_validation_helpers() -> None: ...
def test_flext_auth_session_helper() -> None: ...
