import pytest

from flext_auth import FlextAuth

EXPECTED_DATA_COUNT: int

class TestFlextAuthMainClass:
    @pytest.fixture
    def auth(self) -> FlextAuth: ...
    @pytest.fixture
    def auth_with_config(self) -> FlextAuth: ...
    def test_flext_auth_initialization(self, auth: FlextAuth) -> None: ...
    def test_flext_auth_initialization_with_config(
        self, auth_with_config: FlextAuth
    ) -> None: ...
    @pytest.mark.asyncio
    async def test_user_registration_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_user_registration_REDACTED_LDAP_BIND_PASSWORD_role(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_user_registration_duplicate_fails(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_user_login_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_user_login_invalid_credentials(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_token_validation_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_token_validation_invalid_token(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_logout_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_refresh_token_success(self, auth: FlextAuth) -> None: ...

class TestFlextAuthHelpers:
    def test_quick_start_default(self) -> None: ...
    def test_quick_start_custom_REDACTED_LDAP_BIND_PASSWORD(self) -> None: ...
    def test_hash_password_basic(self) -> None: ...
    def test_hash_password_custom_rounds(self) -> None: ...
    def test_verify_password_correct(self) -> None: ...
    def test_verify_password_incorrect(self) -> None: ...
    def test_generate_jwt_basic(self) -> None: ...
    def test_generate_jwt_with_secret_and_expiration(self) -> None: ...
    def test_decode_jwt_valid(self) -> None: ...
    def test_decode_jwt_invalid(self) -> None: ...
    def test_validate_email_valid_addresses(self) -> None: ...
    def test_validate_email_invalid_addresses(self) -> None: ...
    def test_validate_password_strength_strong(self) -> None: ...
    def test_validate_password_strength_weak(self) -> None: ...
    def test_create_secure_session(self) -> None: ...
    def test_middleware_factory(self) -> None: ...

class TestFlextAuthIntegration:
    @pytest.mark.asyncio
    async def test_complete_auth_flow(self) -> None: ...
    def test_helpers_chain_workflow(self) -> None: ...
    def test_massive_code_reduction_demo(self) -> None: ...

class TestFlextAuthConfiguration:
    def test_flext_auth_config_import(self) -> None: ...
    def test_flext_result_import(self) -> None: ...

class TestPublicInterface:
    def test_all_public_items_importable(self) -> None: ...
    def test_root_namespace_only_access(self) -> None: ...
    def test_no_internal_imports_needed(self) -> None: ...
