EXPECTED_DATA_COUNT: int

class TestFlextAuthDecorators:
    def test_flext_auth_required_with_valid_token(self) -> None: ...
    def test_flext_auth_required_with_invalid_token(self) -> None: ...
    def test_flext_auth_required_without_token(self) -> None: ...
    def test_flext_auth_role_required_with_correct_role(self) -> None: ...
    def test_flext_auth_role_required_with_wrong_role(self) -> None: ...
    def test_flext_auth_permission_required_with_valid_permission(self) -> None: ...
    def test_flext_auth_permission_required_without_permission(self) -> None: ...

class TestFlextAuthUltraHelpers:
    def test_flext_auth_one_liner_success(self) -> None: ...
    def test_flext_auth_one_liner_invalid_email(self) -> None: ...
    def test_flext_auth_one_liner_weak_password(self) -> None: ...
    def test_flext_auth_one_liner_missing_fields(self) -> None: ...
    def test_flext_auth_instant_api_success(self) -> None: ...
    def test_flext_auth_instant_api_with_custom_params(self) -> None: ...
    def test_flext_auth_instant_api_invalid_expires(self) -> None: ...
    def test_flext_auth_instant_api_missing_params(self) -> None: ...
    def test_flext_auth_check_token_valid(self) -> None: ...
    def test_flext_auth_check_token_invalid(self) -> None: ...
    def test_flext_auth_check_token_invalid_format(self) -> None: ...
    def test_flext_auth_check_token_empty(self) -> None: ...

class TestFlextAuthMixin:
    def test_mixin_initialization(self) -> None: ...
    def test_mixin_get_current_user_valid_token(self) -> None: ...
    def test_mixin_get_current_user_invalid_token(self) -> None: ...
    def test_mixin_get_current_user_no_token(self) -> None: ...
    def test_mixin_check_permission_success(self) -> None: ...
    def test_mixin_check_permission_failure(self) -> None: ...
    def test_mixin_create_session_success(self) -> None: ...
    def test_mixin_create_session_invalid_credentials(self) -> None: ...
