class TestFlextAuthBasics:
    def test_flext_auth_instantiation(self) -> None: ...
    def test_quick_start_functionality(self) -> None: ...
    def test_password_hashing(self) -> None: ...
    def test_jwt_generation_and_validation(self) -> None: ...
    def test_flext_result_pattern(self) -> None: ...

class TestFlextAuthIntegration:
    def test_full_authentication_flow(self) -> None: ...
    def test_authentication_with_invalid_credentials(self) -> None: ...
