EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class TestDatabaseConfig:
    def test_database_config_defaults(self) -> None: ...
    def test_database_config_env_vars(self) -> None: ...
    def test_database_url_validation_valid_postgresql(self) -> None: ...
    def test_database_url_validation_valid_asyncpg(self) -> None: ...
    def test_database_url_validation_empty_allowed(self) -> None: ...
    def test_database_url_validation_invalid(self) -> None: ...
    def test_database_pool_size_validation(self) -> None: ...

class TestJWTConfig:
    def test_jwt_config_defaults(self) -> None: ...
    def test_jwt_config_env_vars(self) -> None: ...
    def test_jwt_algorithm_validation_valid(self) -> None: ...
    def test_jwt_algorithm_validation_invalid(self) -> None: ...
    def test_jwt_secret_key_validation_empty_error(self) -> None: ...
    def test_jwt_secret_key_validation_short_error(self) -> None: ...
    def test_jwt_secret_key_validation_valid(self) -> None: ...
    def test_jwt_generate_secret_key(self) -> None: ...

class TestSecurityConfig:
    def test_security_config_defaults(self) -> None: ...
    def test_security_config_env_vars(self) -> None: ...
    def test_security_config_validation_ranges(self) -> None: ...

class TestAppConfig:
    def test_app_config_defaults(self) -> None: ...
    def test_app_config_env_vars(self) -> None: ...
    def test_app_config_model_dump_safe(self) -> None: ...
    def test_app_config_model_dump_safe_no_credentials(self) -> None: ...
    def test_validate_production_config_valid(self) -> None: ...
    def test_validate_production_config_missing_db(self) -> None: ...
    def test_validate_production_config_missing_jwt_secret(self) -> None: ...
