import pytest

from flext_auth import FlextAuth

EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class TestFlextAuthEnhancedABI:
    @pytest.fixture
    def auth(self) -> FlextAuth: ...
    @pytest.mark.asyncio
    async def test_register_validated_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_register_validated_weak_password(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_register_validated_invalid_email(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_register_validated_without_password_check(
        self, auth: FlextAuth
    ) -> None: ...
    @pytest.mark.asyncio
    async def test_login_and_validate_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_login_and_validate_invalid_credentials(
        self, auth: FlextAuth
    ) -> None: ...
    @pytest.mark.asyncio
    async def test_create_user_session_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_create_user_session_without_user_data(
        self, auth: FlextAuth
    ) -> None: ...

class TestEnhancedHelpers:
    def test_quick_start_with_create_REDACTED_LDAP_BIND_PASSWORD_false(self) -> None: ...
    def test_quick_start_with_custom_config(self) -> None: ...
    def test_create_secure_session_with_permissions(self) -> None: ...
    def test_create_secure_session_without_permissions(self) -> None: ...
    def test_enhanced_middleware_factory(self) -> None: ...
    def test_create_api_key(self) -> None: ...
    def test_validate_api_key_success(self) -> None: ...
    def test_validate_api_key_invalid(self) -> None: ...
    def test_validate_api_key_wrong_type(self) -> None: ...

class TestFlextAuthBatchOperations:
    @pytest.fixture
    def auth(self) -> FlextAuth: ...
    def test_batch_operations_creation(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_batch_register_multiple_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_batch_register_multiple_validation_off(
        self, auth: FlextAuth
    ) -> None: ...
    @pytest.mark.asyncio
    async def test_batch_register_multiple_with_errors(
        self, auth: FlextAuth
    ) -> None: ...

class TestIntegrationAdvanced:
    @pytest.mark.asyncio
    async def test_complete_enhanced_workflow(self) -> None: ...
    def test_helpers_chain_advanced(self) -> None: ...

class TestNewEnhancedHelpers:
    def test_create_role_hierarchy(self) -> None: ...
    def test_validate_permissions_success(self) -> None: ...
    def test_validate_permissions_failure(self) -> None: ...
    def test_create_service_token(self) -> None: ...
    def test_create_multi_factor_token(self) -> None: ...
    def test_extract_user_context_user_token(self) -> None: ...
    def test_extract_user_context_service_token(self) -> None: ...
    def test_extract_user_context_invalid_token(self) -> None: ...
    def test_create_auth_context_with_permissions(self) -> None: ...
    def test_create_auth_context_without_permissions(self) -> None: ...
    def test_create_auth_context_invalid_token(self) -> None: ...

class TestBatchOperationsAdvanced:
    @pytest.fixture
    def auth(self) -> FlextAuth: ...
    @pytest.mark.asyncio
    async def test_validate_multiple_tokens_success(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_validate_multiple_tokens_mixed(self, auth: FlextAuth) -> None: ...
    @pytest.mark.asyncio
    async def test_create_multiple_sessions_success(self, auth: FlextAuth) -> None: ...

class TestPublicInterfaceEnhanced:
    def test_all_enhanced_items_importable(self) -> None: ...
    def test_enhanced_namespace_access(self) -> None: ...
    def test_massive_code_reduction_validation(self) -> None: ...
