class TestFlextUser:
    def test_user_creation(self) -> None: ...
    def test_user_is_active(self) -> None: ...
    def test_user_is_locked(self) -> None: ...
    def test_user_is_REDACTED_LDAP_BIND_PASSWORD(self) -> None: ...
    def test_user_validate_business_rules(self) -> None: ...
    def test_user_domain_validation(self) -> None: ...

class TestFlextSession:
    def test_session_creation(self) -> None: ...
    def test_session_is_valid(self) -> None: ...
    def test_session_validate_business_rules(self) -> None: ...

class TestFlextPermission:
    def test_permission_creation(self) -> None: ...
    def test_permission_is_valid(self) -> None: ...
    def test_permission_validate_business_rules(self) -> None: ...

class TestFlextRole:
    def test_role_creation(self) -> None: ...
    def test_role_has_permission(self) -> None: ...
    def test_role_validate_business_rules(self) -> None: ...
