class TestFlextAuthenticationService:
    def test_authentication_service_creation(self) -> None: ...
    def test_create_user_success(self) -> None: ...
    def test_create_user_invalid_username(self) -> None: ...
    def test_create_user_invalid_email(self) -> None: ...
    def test_create_user_invalid_password(self) -> None: ...
    def test_authenticate_user_success(self) -> None: ...
    def test_authenticate_user_wrong_password(self) -> None: ...
    def test_authenticate_user_not_found(self) -> None: ...
    def test_change_password_success(self) -> None: ...
    def test_change_password_wrong_old_password(self) -> None: ...
    def test_change_password_invalid_new_password(self) -> None: ...

class TestFlextSessionService:
    def test_session_service_creation(self) -> None: ...
    def test_create_session_success(self) -> None: ...
    def test_create_session_with_defaults(self) -> None: ...
    def test_validate_session_success(self) -> None: ...
    def test_validate_session_expired(self) -> None: ...
    def test_validate_session_revoked(self) -> None: ...

class TestFlextAuthorizationService:
    def test_authorization_service_creation(self) -> None: ...
    def test_create_role_success(self) -> None: ...
    def test_create_role_with_no_permissions(self) -> None: ...
    def test_create_role_invalid_name(self) -> None: ...
    def test_check_permission_success(self) -> None: ...
    def test_check_permission_no_roles(self) -> None: ...
    def test_check_permission_REDACTED_LDAP_BIND_PASSWORD_user(self) -> None: ...
