from _typeshed import Incomplete

from flext_auth import (
    FlextAuthClaims as FlextAuthClaims,
    FlextAuthHeaders as FlextAuthHeaders,
    FlextAuthPermissions as FlextAuthPermissions,
    FlextAuthRole as FlextAuthRole,
    FlextAuthSessionData as FlextAuthSessionData,
    FlextAuthTokenData as FlextAuthTokenData,
    FlextAuthUserData as FlextAuthUserData,
)

HTTP_OK: int

class TestTypedefs:
    def test_type_aliases_are_correct_types(self) -> None: ...

class TestFlextAuthMixin:
    def test_mixin_add_validation(self) -> None: ...
    def test_mixin_get_headers(self) -> None: ...

class TestFlextAuthUserMixin:
    id: Incomplete
    username: Incomplete
    email: Incomplete
    role: Incomplete
    permissions: Incomplete
    def test_user_context_extraction(self) -> None: ...
    def test_permission_checking(self) -> None: ...
    def test_resource_access_control(self) -> None: ...

class TestFlextAuthSessionMixin:
    def test_session_refresh(self) -> None: ...
    def test_session_validation(self) -> None: ...

class TestDictHelpers:
    def test_merge_configs(self) -> None: ...
    def test_create_user_payload(self) -> None: ...
    def test_extract_token_claims(self) -> None: ...
    def test_build_response(self) -> None: ...
    def test_filter_user_data(self) -> None: ...

class TestSpecializedDecorators:
    def test_role_required_decorator(self) -> None: ...
    def test_permission_required_decorator(self) -> None: ...
    def test_rate_limit_decorator(self) -> None: ...
    def test_decorators_without_token(self) -> None: ...

class TestIntegration:
    def test_mixin_with_helpers(self) -> None: ...
    def test_end_to_end_workflow(self) -> None: ...
