EXPECTED_BULK_SIZE: int

class TestJWTService:
    def test_jwt_service_creation(self) -> None: ...
    def test_jwt_service_creation_minimal(self) -> None: ...
    def test_generate_access_token_success(self) -> None: ...
    def test_generate_access_token_with_extra_claims(self) -> None: ...
    def test_generate_refresh_token_success(self) -> None: ...
    def test_verify_token_success(self) -> None: ...
    def test_verify_token_invalid(self) -> None: ...
    def test_verify_token_expired(self) -> None: ...
    def test_verify_token_wrong_secret(self) -> None: ...
    def test_refresh_token_flow(self) -> None: ...
    def test_get_token_claims_success(self) -> None: ...
    def test_get_token_claims_invalid_token(self) -> None: ...
    def test_token_expiration_validation(self) -> None: ...
    def test_different_algorithms(self) -> None: ...
    def test_jwt_claims_validation(self) -> None: ...
